//program to demonstrate inheritance
//1. single inheritance

#include <iostream.h>
#include <conio.h>

/*class base
{
  public:
  int a;
  void get();
};
void base::get()
{
  cout<<"enter value of a:"<<endl;
  cin>>a;
}
class derived:public base
{
  public:
  void show();
};
void derived::show()
{
  cout<<"value of a is:\n"<<a<<endl;
}
void main()
{
  clrscr();
  derived d;
  d.get();
  d.show();
  getch();
}

//multiple inheritance

class a
{
  public:
  int a;
  void get();
};
void a::get()
{
  cout<<"enter value of a:"<<endl;
  cin>>a;
}
class b
{
  public:
  int b;
  void read();
};
void b::read()
{
  cout<<"enter value of b:"<<endl;
  cin>>b;
}
class c:public a,public b
{
  public:
  void show();
};
void c::show()
{
  cout<<"value of a is:"<<a<<endl;
  cout<<"value of b is:"<<b<<endl;
}
void main()
{
  clrscr();
  c c1;
  c1.get();
  c1.read();
  c1.show();
  getch();
}

//multilevel inheritance

class a
{
  public:
  int a;
  void get();
};
void a::get()
{
  cout<<"enter value of a:"<<endl;
  cin>>a;
}
class b:public a
{
  public:
  int b;
  void read();
};
void b::read()
{
  cout<<"enter value of b:"<<endl;
  cin>>b;
}
class c:public b
{
  public:
  int sum;
  void add();
};
void c::add()
{
  sum=a+b;
  cout<<"addition of two numbers is:"<<sum<<endl;
}
void main()
{
  clrscr();
  c c1;
  c1.get();
  c1.read();
  c1.add();
  getch();
}*/





